"""remove latex fields

Revision ID: 0698cc218a95
Revises: dff100da4ec7
Create Date: 2026-09-17 09:56:35.308613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0698cc218a95'
down_revision: Union[str, None] = 'dff100da4ec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master_resumes', 'assets_paths')
    op.drop_column('master_resumes', 'original_tex_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_resumes', sa.Column('original_tex_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('master_resumes', sa.Column('assets_paths', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
